source 'https://rubygems.org'

# Specify your gem's dependencies in google_maps_service.gemspec
gemspec

group :development do
  gem 'bundler', '~> 1.6'
  gem 'rake', '~> 10.0'
  gem 'rspec', '~> 3.3'
end

if ENV['RAILS_VERSION']
  gem 'rails', ENV['RAILS_VERSION']
end
